#
#
# Example "users.toml". Lines starting with "#" are comments.
# This shows example users.
#
member_of = [ "admin" ]
["Jane.Doe"]
display_name = "Jane Doe"
member_of = ["publisher"]
["Millie.Flowers"]
display_name = "Millie Flowers"
member_of = [ "editor" ]
["Innes.Mars"]
display_name = "Innes Mars"
member_of = [ "writer" ]
