#
#
# Example "users.toml". Lines starting with "#" are comments.
# This shows example users.
#
["Jane"]
display_name = "Jane Doe"
member_of = ["publisher"]
["Millie"]
display_name = "Millie Flowers"
member_of = [ "editor" ]
["Innez"]
display_name = "Innez Mars"
member_of = [ "writer" ]
