#
# Example "workflows.toml". Lines starting with "#" are comments.
# This file setups up the workflows used by AndOr.
#
[publisher]
workflow_name = "Publisher"
queue = "*"
create = true
read = true
update = true
delete = true
assign_to = [ "*" ]

[editor]
workflow_name = "Editor"
queue = "review"
create = true
read = true
update = true
delete = true
assign_to = [ "inbox", "embargoed", "published"  ]

[writer]
workflow_name = "Writer"
queue = "inbox"
create = true
read =  true
update = true
delete = true
assign_to = [ "review" ]

[embargoed]
workflow_name = "Embargoed"
queue = "embargoed"
create = false
read = true
update = false
delete = false
assign_to = [ "review" ]

[published]
workflow_name = "Published"
queue = "published"
create = false
read = true
update = false
delete = false
assign_to = [ ]

