# Generated by Django 2.2.7 on 2019-11-07 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('CL_PEOPLE_ID', models.CharField(help_text='The common ID used between Caltech Library systems, often the Creator ID from CaltechAUTHORS', max_length=256, primary_key=True, serialize=False)),
                ('Family_Name', models.CharField(help_text="The family of the individual, e.g. John Steinbeck would be 'Steinbeck'", max_length=256)),
                ('Given_Name', models.CharField(help_text="The given name of an individual, e.g. John Steinbeck would be 'John'", max_length=256)),
                ('Thesis_ID', models.CharField(help_text='The creator ID used in CaltechTHESIS', max_length=256)),
                ('Advisor_ID', models.CharField(help_text='The advisor id used in CatechTHESIS', max_length=256)),
                ('Authors_ID', models.CharField(help_text='The creator ID used in CaltechAUTHORS', max_length=256)),
                ('ArchivesSpace_ID', models.CharField(help_text='The agent:person id used in ArchivesSpace', max_length=256)),
                ('Directory_ID', models.CharField(help_text='The directory user id used in the Caltech Directory', max_length=256)),
                ('VIAF_ID', models.CharField(help_text='The VIAF if avaialble', max_length=256)),
                ('LCNAF', models.CharField(help_text='The LCNAF if available', max_length=256)),
                ('ISNI', models.CharField(help_text='The ISNI if available', max_length=256)),
                ('Wikidata', models.CharField(help_text='The wikidata id if available', max_length=256)),
                ('SNAC', models.CharField(help_text='The SNAC if available', max_length=256)),
                ('ORCID', models.CharField(help_text='The ORCID if available', max_length=256)),
                ('image', models.CharField(help_text='A URL to an image of the individual', max_length=256)),
                ('educated_at', models.TextField(help_text='A free form text description of past education')),
                ('Caltech', models.BooleanField(help_text='True if associated with Caltech')),
                ('JPL', models.BooleanField(help_text='True if associated with JPL')),
                ('Faculty', models.BooleanField(help_text='True if Caltech faculty')),
                ('Alumn', models.BooleanField(help_text='True if Caltech Alumni')),
                ('Notes', models.TextField(help_text='Internal processing notes')),
                ('Created', models.DateTimeField(auto_now_add=True, help_text='Date object was created')),
                ('Updated', models.DateTimeField(auto_now=True, help_text='Date object was updated')),
            ],
        ),
    ]
