# Generated by Django 2.2.7 on 2019-11-07 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='Advisor_ID',
            field=models.CharField(blank=True, default='', help_text='The advisor id used in CatechTHESIS', max_length=256),
        ),
        migrations.AlterField(
            model_name='people',
            name='Alumn',
            field=models.BooleanField(default=False, help_text='True if Caltech Alumni'),
        ),
        migrations.AlterField(
            model_name='people',
            name='ArchivesSpace_ID',
            field=models.CharField(blank=True, default='', help_text='The agent:person id used in ArchivesSpace', max_length=256),
        ),
        migrations.AlterField(
            model_name='people',
            name='Authors_ID',
            field=models.CharField(blank=True, default='', help_text='The creator ID used in CaltechAUTHORS', max_length=256),
        ),
        migrations.AlterField(
            model_name='people',
            name='CL_PEOPLE_ID',
            field=models.CharField(help_text='The common ID used between Caltech Library systems, often the Creator ID from CaltechAUTHORS', max_length=256, primary_key=True, serialize=False, verbose_name='Caltech Library People ID'),
        ),
        migrations.AlterField(
            model_name='people',
            name='Caltech',
            field=models.BooleanField(blank=True, default='', help_text='True if associated with Caltech'),
        ),
        migrations.AlterField(
            model_name='people',
            name='Directory_ID',
            field=models.CharField(blank=True, default='', help_text='The directory user id used in the Caltech Directory', max_length=256),
        ),
        migrations.AlterField(
            model_name='people',
            name='Faculty',
            field=models.BooleanField(default=False, help_text='True if Caltech faculty'),
        ),
        migrations.AlterField(
            model_name='people',
            name='ISNI',
            field=models.CharField(blank=True, default='', help_text='The ISNI if available', max_length=256),
        ),
        migrations.AlterField(
            model_name='people',
            name='JPL',
            field=models.BooleanField(default=False, help_text='True if associated with JPL'),
        ),
        migrations.AlterField(
            model_name='people',
            name='LCNAF',
            field=models.CharField(blank=True, default='', help_text='The LCNAF if available', max_length=256),
        ),
        migrations.AlterField(
            model_name='people',
            name='Notes',
            field=models.TextField(blank=True, default='', help_text='Internal processing notes'),
        ),
        migrations.AlterField(
            model_name='people',
            name='ORCID',
            field=models.CharField(blank=True, default='', help_text='The ORCID if available', max_length=256),
        ),
        migrations.AlterField(
            model_name='people',
            name='SNAC',
            field=models.CharField(blank=True, default='', help_text='The SNAC if available', max_length=256),
        ),
        migrations.AlterField(
            model_name='people',
            name='Thesis_ID',
            field=models.CharField(blank=True, default='', help_text='The creator ID used in CaltechTHESIS', max_length=256),
        ),
        migrations.AlterField(
            model_name='people',
            name='VIAF_ID',
            field=models.CharField(blank=True, default='', help_text='The VIAF if avaialble', max_length=256),
        ),
        migrations.AlterField(
            model_name='people',
            name='Wikidata',
            field=models.CharField(blank=True, default='', help_text='The wikidata id if available', max_length=256),
        ),
        migrations.AlterField(
            model_name='people',
            name='educated_at',
            field=models.TextField(blank=True, default='', help_text='A free form text description of past education'),
        ),
        migrations.AlterField(
            model_name='people',
            name='image',
            field=models.CharField(blank=True, default='', help_text='A URL to an image of the individual', max_length=256),
        ),
    ]
