#
# Example "workflows.toml". Lines starting with "#" are comments.
# This file setups up the workflows used by AndOr.
#

[curator]
role_id = "curator"
role_name = "Curator"
states = ["review", "embargoed", "published", "deleted" ]
create = false
read = true
update = true
delete = true
assign_to = ["*"]

[depositor]
role_id = "depositor"
role_name = "Depositor"
states = ["deposit"]
create = true
read = false
update = false
delete = false
assign_to = ["review", "deleted" ]

[public]
role_id = "public"
role_name = "Public"
states = ["published"]
create = false
read = true
update = false
delete = false

[publisher]
role_id = "publisher"
role_name = "Publisher"
states = ["*"]
create = true
read = true
update = true
delete = true
assign_to = ["*"]

